### ISSUE TITLE
Please add a license! :)

### ISSUE THREAD

**Issue by desplesda** [nothke/gridventory#1]
Hi there! This looks super cool, and solves a very common problem. Would you mind please adding a license to the project, so that it can be used in games? (Currently, without a license, the code can't legally be used in other projects.)

I personally like the [MIT license](https://choosealicense.com/licenses/mit/); a great resource for choosing a good license to fit the project is [Choose a License](https://choosealicense.com).

Thanks again for the excellent code, and for posting it publicly here!

**Comment by nothke** [comment]
Oh, thanks for reminding me! I just forgot to add it right away. Ok, added it now :)
